[tool.poetry]
name = "iocingestor"
version = "0.2.0"
description = "Extract and aggregate IOCs from threat feeds."
authors = ["Manabu Niseki <manabu.niseki@gmail.com>", "InQuest Labs <labs@inquest.net>"]
homepage = "https://github.com/ninoseki/iocingestor"
repository = "https://github.com/ninoseki/iocingestor"
license = "GPL-2.0-or-later"

[tool.poetry.dependencies]
python = "^3.6.1"
aiocontextvars = "^0.2.2"
beautifulsoup4 = "^4.8.2"
contextvars = "^2.4"
feedparser = "^5.2.1"
hug = "^2.6.1"
importlib-metadata = "^1.6.0"
ioc-finder = "^4.0.0"
ipaddress = "^1.0.23"
jsonpath-rw = "^1.4.0"
loguru = "^0.5.0"
pymisp = "^2.4.124"
PyYAML = "^5.3.1"
requests = "^2.23.0"
sgmllib3k = "^1.0.0"
statsd = "^3.3.0"
twitter = "^1.18.0"
iocextract = "^1.13.1"
pydantic = "^1.4"
pyparsing = "^2.4.6"

[tool.poetry.dev-dependencies]
autoflake = "^1.3.1"
autopep8 = "^1.5"
black = "^19.10b0"
coverage = "^5.0.4"
coveralls = "^2.0.0"
flake8 = "^3.7.9"
httpretty = "^1.0.2"
isort = "^5.0.0"
mock = "^4.0.2"
mypy = "^0.770"
nose2 = "^0.9.2"
pre-commit = "^2.2.0"
pytest = "^6.0"
pyupgrade = "^2.6.2"
responses = "^0.11.0"
seed-isort-config = "^2.1.1"

[tool.poetry.scripts]
iocingestor = "iocingestor:main"

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
known_third_party = ["bs4", "feedparser", "httpretty", "hug", "ioc_finder", "iocextract", "jsonpath_rw", "loguru", "pydantic", "pymisp", "pyparsing", "requests", "responses", "statsd", "twitter", "yaml"]
line_length = 88
multi_line_output = 3
use_parentheses= true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
